before_script:
  - source /opt/miniconda/bin/activate

build:
  stage: build
  script:
    - cd $CI_COMMIT_REF_NAME
    - conda build . --prefix-length=80 --output-folder=../dist/ --python=2.7
    # - conda build . --prefix-length=80 --output-folder=../dist/ --python=3.6
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - mv -f dist/* /conda/bcu/linux-64/
    - conda index  /conda/bcu/linux-64/