image: registry.gitlab.com/tiagocoutinho/pytango-conda-recipes:build

before_script:
  - source /opt/conda/bin/activate

build27:
  stage: build
  script:
    - cd pytango
    - conda build --no-anaconda-upload --prefix-length=60 --output-folder=../dist/ --python=2.7 .
  artifacts:
    paths:
      - dist/

build35:
  stage: build
  script:
    - cd pytango
    - conda build --no-anaconda-upload --prefix-length=60 --output-folder=../dist/ --python=3.5 .
  artifacts:
    paths:
      - dist/

build36:
  stage: build
  script:
    - cd pytango
    - conda build --no-anaconda-upload --prefix-length=60 --output-folder=../dist/ --python=3.6 .
  artifacts:
    paths:
      - dist/

build37:
  stage: build
  script:
    - cd pytango
    - conda build --no-anaconda-upload --prefix-length=60 --output-folder=../dist/ --python=3.7 .
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - anaconda --token="$ANACONDA_TOKEN" upload dist/linux-64/*.tar.bz2
  only:
    - master

