before_script:
  - source /opt/conda/bin/activate

build27:
  stage: build
  script:
    - cd $CI_COMMIT_REF_NAME
    - conda build . --output-folder=../dist/ --python=2.7 --channel=file://conda --channel=conda-forge
  artifacts:
    paths:
      - dist/

build35:
  stage: build
  script:
    - cd $CI_COMMIT_REF_NAME
    - conda build . --output-folder=../dist/ --python=3.5 --channel=file://conda --channel=conda-forge
  artifacts:
    paths:
      - dist/

build36:
  stage: build
  script:
    - cd $CI_COMMIT_REF_NAME
    - conda build . --output-folder=../dist/ --python=3.6 --channel=file://conda --channel=conda-forge
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - mv -f dist/linux-64/* /conda/linux-64/
    - conda index /conda/linux-64/
