{% set version = "9.2.2" %}

package:
  name: pytango
  version: {{ version }}

source:
  git_url: https://github.com/tango-cs/pytango.git
  git_tag: v{{ version }}

build:
  script: "pip install --no-binary=:all: --ignore-installed --no-deps ."

requirements:
  build:
    - gcc
    - tango 9.2.*
    - boost 1.61.*
    - python
    - numpy
    - pyzmq
  run:
    - libgcc
    - tango 9.2.*
    - boost 1.61.*
    - python
    - numpy
    - pyzmq
    - six

test:
  imports:
    - PyTango
    - tango

about:
  home: http://pytango.rtfd.io
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'Python binding for the TANGO control system'
