{% set version = "9.2.2" %}

package:
  name: pytango
  version: {{ version }}

source:
  git_url: https://github.com/tango-cs/pytango.git
  git_tag: v{{ version }}

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - tango 9.2.*
    - boost 1.60.*
    - python
    - numpy
    - pyzmq
  run:
    - {{ pin_compatible('tango', max_pin='x.x') }}  # Strict pinning
    - {{ pin_compatible('boost', max_pin='x.x') }}  # Strict pinning
    - {{ pin_compatible('pyzmq', min_pin='x') }}  # Loose pinning
    - {{ pin_compatible('numpy', min_pin='x') }}  # Loose pinning
    - python
    - six

test:
  requires:
    - pytest
    - pytest-xdist
    - gevent
    - psutil
    - trollius # [py27]
  source_files:
    - tests/
    - setup.cfg
  imports:
    - PyTango
    - tango
  commands:
    - pytest -k 'server'

about:
  home: http://pytango.rtfd.io
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'Python binding for the TANGO control system'
